import { z } from "zod"
import { candidateSchema } from "@/config/sbTables"

export type Candidate = z.infer<typeof candidateSchema>

export const dummyCandidates: Candidate[] = [
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440001",
    name: "Max Mustermann",
    company: "TechCorp GmbH",
    contact_info: {
      email: "max.mustermann@example.com",
      phone: "+49 151 12345678",
    },
    skills: "React, TypeScript, Node.js, PostgreSQL",
    experience_years: 5,
    qualified: true,
    interview_scheduled: true,
    job_title: "Senior Frontend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440002",
    name: "Anna Schmidt",
    company: "StartupXYZ",
    contact_info: {
      email: "anna.schmidt@example.com",
    },
    skills: "Python, Django, Docker, AWS",
    experience_years: 3,
    qualified: true,
    interview_scheduled: false,
    job_title: "Backend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440003",
    name: "Tom Weber",
    company: "Digital Solutions AG",
    contact_info: {
      email: "tom.weber@example.com",
      phone: "+49 160 98765432",
    },
    skills: "Java, Spring Boot, Microservices, Kubernetes",
    experience_years: 7,
    qualified: true,
    interview_scheduled: true,
    job_title: "Full Stack Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440004",
    name: "Lisa Müller",
    company: "WebDev Inc.",
    contact_info: {
      email: "lisa.mueller@example.com",
    },
    skills: "JavaScript, Vue.js, CSS, HTML",
    experience_years: 2,
    qualified: false,
    interview_scheduled: false,
    job_title: "Junior Frontend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440005",
    name: "David Fischer",
    company: "CloudTech GmbH",
    contact_info: {
      email: "david.fischer@example.com",
      phone: "+49 170 55512345",
    },
    skills: "C#, .NET, SQL Server, Azure",
    experience_years: 6,
    qualified: true,
    interview_scheduled: false,
    job_title: "Backend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440006",
    name: "Sarah Becker",
    company: "InnovateLab",
    contact_info: {
      email: "sarah.becker@example.com",
    },
    skills: "React, Next.js, TailwindCSS, TypeScript",
    experience_years: 4,
    qualified: true,
    interview_scheduled: true,
    job_title: "Frontend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440007",
    name: "Michael Koch",
    company: "Enterprise Systems",
    contact_info: {
      email: "michael.koch@example.com",
      phone: "+49 175 77788899",
    },
    skills: "PHP, Laravel, MySQL, Redis",
    experience_years: 8,
    qualified: true,
    interview_scheduled: true,
    job_title: "Senior Backend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440008",
    name: "Julia Wagner",
    company: "AppWorks",
    contact_info: {
      email: "julia.wagner@example.com",
    },
    skills: "Angular, TypeScript, RxJS, NgRx",
    experience_years: 3,
    qualified: false,
    interview_scheduled: false,
    job_title: "Frontend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440009",
    name: "Chris Hoffmann",
    company: "DevOps Solutions",
    contact_info: {
      email: "chris.hoffmann@example.com",
      phone: "+49 152 33344455",
    },
    skills: "Go, REST APIs, GraphQL, MongoDB",
    experience_years: 5,
    qualified: true,
    interview_scheduled: false,
    job_title: "Backend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440010",
    name: "Maria Schulz",
    company: "MobileFirst",
    contact_info: {
      email: "maria.schulz@example.com",
    },
    skills: "React Native, Flutter, Firebase, iOS, Android",
    experience_years: 4,
    qualified: true,
    interview_scheduled: true,
    job_title: "Mobile Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440011",
    name: "Peter Klein",
    company: "RubyRails GmbH",
    contact_info: {
      email: "peter.klein@example.com",
      phone: "+49 151 99988877",
    },
    skills: "Ruby, Rails, PostgreSQL, Heroku",
    experience_years: 6,
    qualified: false,
    interview_scheduled: false,
    job_title: "Full Stack Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440012",
    name: "Nina Bauer",
    company: "VueVentures",
    contact_info: {
      email: "nina.bauer@example.com",
    },
    skills: "Vue.js, Nuxt.js, Pinia, Vite",
    experience_years: 3,
    qualified: true,
    interview_scheduled: false,
    job_title: "Frontend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440013",
    name: "Felix Schneider",
    company: "FullStack Pro",
    contact_info: {
      email: "felix.schneider@example.com",
      phone: "+49 163 11122233",
    },
    skills: "TypeScript, React, Node.js, Express, MongoDB",
    experience_years: 4,
    qualified: true,
    interview_scheduled: true,
    job_title: "Full Stack Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440014",
    name: "Sophie Richter",
    company: "PythonDev",
    contact_info: {
      email: "sophie.richter@example.com",
    },
    skills: "Python, Flask, FastAPI, PostgreSQL, Docker",
    experience_years: 2,
    qualified: false,
    interview_scheduled: false,
    job_title: "Junior Backend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440015",
    name: "Lukas Zimmermann",
    company: "iOS Experts",
    contact_info: {
      email: "lukas.zimmermann@example.com",
      phone: "+49 174 44455566",
    },
    skills: "Swift, iOS Development, UIKit, SwiftUI, Core Data",
    experience_years: 5,
    qualified: true,
    interview_scheduled: false,
    job_title: "iOS Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440016",
    name: "Emma Lehmann",
    company: "React Masters",
    contact_info: {
      email: "emma.lehmann@example.com",
    },
    skills: "JavaScript, React, Redux, Jest, Cypress",
    experience_years: 6,
    qualified: true,
    interview_scheduled: true,
    job_title: "Senior Frontend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440017",
    name: "Jonas Wolf",
    company: "Android Studio",
    contact_info: {
      email: "jonas.wolf@example.com",
      phone: "+49 175 66677788",
    },
    skills: "Kotlin, Android, Jetpack Compose, Room, Retrofit",
    experience_years: 4,
    qualified: true,
    interview_scheduled: true,
    job_title: "Android Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440018",
    name: "Hannah Meier",
    company: "PHP Solutions",
    contact_info: {
      email: "hannah.meier@example.com",
    },
    skills: "PHP, Symfony, Doctrine, MySQL, Redis",
    experience_years: 3,
    qualified: false,
    interview_scheduled: false,
    job_title: "Backend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440019",
    name: "Benjamin Huber",
    company: "Rust Labs",
    contact_info: {
      email: "benjamin.huber@example.com",
      phone: "+49 176 88899900",
    },
    skills: "Rust, WebAssembly, Actix, Tokio, PostgreSQL",
    experience_years: 7,
    qualified: true,
    interview_scheduled: false,
    job_title: "Senior Backend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440020",
    name: "Laura König",
    company: "Svelte Solutions",
    contact_info: {
      email: "laura.koenig@example.com",
    },
    skills: "Svelte, SvelteKit, TypeScript, TailwindCSS, Vite",
    experience_years: 3,
    qualified: true,
    interview_scheduled: true,
    job_title: "Frontend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440021",
    name: "Alexander Stein",
    company: "Elixir Experts",
    contact_info: {
      email: "alexander.stein@example.com",
      phone: "+49 177 00011122",
    },
    skills: "Elixir, Phoenix, LiveView, PostgreSQL, OTP",
    experience_years: 5,
    qualified: true,
    interview_scheduled: false,
    job_title: "Backend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440022",
    name: "Mia Lang",
    company: "Junior Devs",
    contact_info: {
      email: "mia.lang@example.com",
    },
    skills: "HTML, CSS, JavaScript, jQuery, Bootstrap",
    experience_years: 1,
    qualified: false,
    interview_scheduled: false,
    job_title: "Junior Frontend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440023",
    name: "Noah Braun",
    company: "Scala Systems",
    contact_info: {
      email: "noah.braun@example.com",
      phone: "+49 178 22233344",
    },
    skills: "Scala, Akka, Spark, Kafka, Cassandra",
    experience_years: 8,
    qualified: true,
    interview_scheduled: true,
    job_title: "Senior Backend Developer",
  },
  {
    candidate_id: "550e8400-e29b-41d4-a716-446655440024",
    name: "Lea Sommer",
    company: "Next.js Pro",
    contact_info: {
      email: "lea.sommer@example.com",
    },
    skills: "Next.js, React, TypeScript, Prisma, PostgreSQL, tRPC",
    experience_years: 4,
    qualified: true,
    interview_scheduled: false,
    job_title: "Full Stack Developer",
  },
]

